# Generated by Django 4.2.2 on 2023-06-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=20)),
                ("phone", models.CharField(max_length=15)),
                ("description", models.TextField(max_length=200)),
                ("image", models.ImageField(upload_to="about/")),
            ],
        ),
    ]
