# Generated by Django 4.2.2 on 2023-06-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0002_rename_full_name_about_first_name_about_last_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("university", models.CharField(max_length=50)),
                ("degree", models.CharField(max_length=50)),
                ("department", models.CharField(max_length=50)),
                ("result", models.CharField(max_length=50)),
            ],
        ),
    ]
