# Generated by Django 4.2.2 on 2023-06-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0005_education_end_year_education_start_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=30)),
                ("project_link", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=1000)),
                ("thumbnail", models.ImageField(upload_to="thumbnails/")),
            ],
        ),
    ]
